name: Run Tests
run-name: Tests run on ${{ github.event.repository.pushed_at }}
on:
  push:
  pull_request:


jobs:
  test-py36:
    uses: ./.github/workflows/test_3.6.yaml
  test-py38:
    uses: ./.github/workflows/test_3.8.yaml
